# Generated by Django 4.1.3 on 2023-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob',
            field=models.IntegerField(unique=True),
        ),
    ]
