# Generated by Django 4.1.3 on 2023-02-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_student_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email1',
            new_name='Email',
        ),
    ]
