# Generated by Django 4.1.3 on 2023-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_rename_email1_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AddField(
            model_name='student',
            name='Email_address',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
    ]
