# Generated by Django 4.1.3 on 2023-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
